- name: copy catalogue service to system directory
  template:
    src: catalogue.service.j2
    dest: /etc/systemd/system/catalogue.service

- name: systemctl daemon reload
  systemd_service:
    daemon_reload: true

- name: Start and enable catalogue
  service: 
    name: catalogue
    state: restarted #even app is not running we can restart 
    enabled: yes 